import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import vono from "@vonojs/vono";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), vono()],
  ssr: {
    external: [
      "node:fs",
      "node:path",
      "node:os",
      "node:crypto",
      "node:stream",
      "node:buffer",
      "node:events",
      "node:util",
      "node:assert",
      "node:zlib",
      "node:http",
      "node:https",
      "node:net",
      "node:tls",
      "node:dns",
      "node:querystring",
      "node:assert",
      "node:timers",
      "node:child_process",
      "node:cluster",
      "node:dgram",
      "node:module",
      "node:perf_hooks",
      "node:readline",
      "node:repl",
      "node:vm",
      "node:worker_threads",
      "node:fs/promises",
      "node:os",
      "node:process",
      "node:crypto",
      "node:stream",
      "node:buffer",
      "node:events",
      "node:util",
      "node:assert",
      "node:zlib",
      "node:http",
      "node:https",
      "node:net",
      "node:tls",
      "node:dns",
      "node:querystring",
      "node:assert",
      "node:timers",
      "node:child_process",
      "node:cluster",
      "node:dgram",
      "node:module",
      "node:perf_hooks",
      "node:readline",
      "node:repl",
      "node:vm",
      "node:worker_threads",
      "node:fs/promises",
      "node:os",
      "node:process",
      "node:crypto",
      "node:stream",
      "node:buffer",
      "node:events",
      "node:util",
      "node:assert",
      "node:zlib",
      "node:http",
      "node:https",
      "node:net",
      "node:tls",
      "node:dns",
      "node:querystring",
      "node:assert",
      "node:timers",
      "node:child_process",
      "node:cluster",
      "node:dgram",
      "node:module",
      "node:perf_hooks",
      "node:readline",
      "node:repl",
      "node:vm",
      "node:worker_threads",
      "node:fs/promises",
      "node:url",
      "node:stream/web",
    ],
  },
});
